spring:
  profiles:
    active: dev

swagger:
  production: false
  basic:
    enable: false
    username: jeecg
    password: jeecg1314
dubbo:
  application:
    name: ksf-provider
  scan:
    base-packages: org.jeecg
# Dubbo Protocol
  protocol:
    name: dubbo
  ## Random port
    port: -1
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
## DemoService version
ksf:
  service:
    version: 1.0.0
embedded:
  zookeeper:
    port : 2181